### PR TITLE
Fix ParsedLightTypeTag110 hashCode

### LINKED ISSUE #4739: Potential Scala 3 Compatibility Issue With Tags
This program runs correctly on Scala 2 but fails on Scala 3:

```scala
import zio._
import zio.console._

object Example {

  type FakeExchange = Has[FakeExchange.Service]

  object FakeExchange {
    trait Service {
      def blah(): UIO[Unit]
    }
    def blah(): ZIO[FakeExchange, Nothing, Unit] = ZIO.accessM(_.get.blah())
    val fakeExchangeLayer: ZLayer[Any, Nothing, FakeExchange] =
      ZLayer.succeed {
        new FakeExchange.Service {
          override def blah() = UIO.unit
        }
      }
  }
}

object Main extends App {
  import Example._
  import Example.FakeExchange.fakeExchangeLayer
  def run(args: List[String]) = {
    val infra = ZLayer.requires[zio.console.Console] ++ ZLayer.requires[zio.clock.Clock] ++
      ZLayer.requires[zio.blocking.Blocking] ++ ZLayer.requires[zio.random.Random]
    type TargetEnv = zio.console.Console
      with zio.clock.Clock
      with zio.blocking.Blocking
      with FakeExchange
      with zio.random.Random
    val finalLayer: ZLayer[
      zio.random.Random with zio.console.Console with zio.clock.Clock with zio.blocking.Blocking,
      Nothing,
      TargetEnv
    ] =
      infra >+> fakeExchangeLayer
    val program2: ZIO[TargetEnv, Nothing, Int] = ZIO.succeed(0)
    (putStrLn("running...") *> program2).provideCustomLayer(finalLayer).exitCode
  }
}
```

The error message on Scala 3 is:

```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: HashSet(Example$::FakeExchange$::Service, package$::Console$::Service, package$::Random$::Service, package$::Blocking$::Service, package$::Clock$::Service) statically known to be contained within the environment are missing
```

Given that it works correctly on Scala 2 I am thinking that this is an issue with the `Tag` machinery and the way it interacts with Scala 3.

@neko-kai Could you take a look when you have the chance?

### PR DESCRIPTION
**Pull request by Lermex**
Fixes https://github.com/zio/zio/issues/4739 / https://github.com/zio/zio/issues/4809

The `ParsedLightTypeTag110` instances generated by the Dotty macro in `dottyreflection/Inspect.scala` were using the ref hashCode directly while the `hashCode` function in `LightTypeTag.scala` has the following implementation:
```
private[this] lazy val hashcode: Int = {
  ref.hashCode() * 31
}
```
this made all `ParsedLightTypeTag110` instances fail `hashCode` comparisons with `LightTypeTag` instances on Dotty.

Scala 2 wasn't affected because the Scala 2 macro constructs a full `LightTypeTag` instance to delegate to its `hashCode` function:
```
final def makeParsedLightTypeTagImpl(tpe: Type): c.Expr[LightTypeTag] = {
    val res = impl.makeFullTagImpl(tpe)

    logger.log(s"LightTypeTagImpl: created LightTypeTag: $res")

    val hashCodeRef = res.hashCode()
    val strRef = PickleImpl.serializeIntoString(res.ref, LightTypeTag.lttRefSerializer)
    val strDBs = PickleImpl.serializeIntoString(SubtypeDBs(res.basesdb, res.idb), LightTypeTag.subtypeDBsSerializer)

    c.Expr[LightTypeTag](
      q"_root_.izumi.reflect.macrortti.LightTypeTag.parse($hashCodeRef: _root_.scala.Int, $strRef : _root_.java.lang.String, $strDBs : _root_.java.lang.String, ${LightTypeTag.currentBinaryFormatVersion}: _root_.scala.Int)"
    )
  }
```

### CODE REVIEW

File: izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspect.scala [hunk 1]
```diff
@@ -33,6 +33,6 @@ object Inspect {
       println(s"$dbs => ${strDbs.size} bytes, ${string2hex(strDbs)}")
       println(strDbs)
     }
-    '{ LightTypeTag.parse(${Expr(ref.hashCode())}, ${Expr(strRef)}, ${Expr(strDbs)}, ${Expr(LightTypeTag.currentBinaryFormatVersion)}) }
+    '{ LightTypeTag.parse(${Expr(ref.hashCode() * 31)}, ${Expr(strRef)}, ${Expr(strDbs)}, ${Expr(LightTypeTag.currentBinaryFormatVersion)}) }
```
Comment (Lermex) [inline izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspect.scala]: Should I extract a common function, e.g. `LightTypeTag.hashCodeFromRef`?

Comment (neko-kai) [reply izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspect.scala]: @Lermex Thanks for taking the time to debug this! 🙏 

Instead of doing `* 31` manually here, we should construct the full LightTypeTag instance in Scala 3 version too, to prevent another desync in the future, e.g. you may change the lines above to

```scala
    val res = {
      val ref = TypeInspections.apply[T]
      val fullDb = TypeInspections.fullDb[T]
      val nameDb = TypeInspections.nameDb[T]
      LightTypeTag(ref, fullDb, nameDb)
    }
```

And make the rest as identical to the Scala 2 version as possible.

**Review by pshirshov — APPROVED** [review]

**Comment by neko-kai** [comment]
@Lermex Thank you! 🙏

**Comment by Lermex** [comment]
@neko-kai sorry I couldn't find the time to address the review comments. Thank you for taking over :)
