### PR TITLE
Fix cached refined type issue (sorta)

### LINKED ISSUE #6071: Macro expansion exception when upgrading from 2.0.0-M4 to 2.0.0-M6-2
When upgrading from 2.0.0-M4 to 2.0.0-M6-2, I [started getting a compile-time exception][1] when using `ZLayer.succeed` without an explicit type argument:

```
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.RuntimeException: TYPEREPR, UNSUPPORTED: class dotty.tools.dotc.core.Types$CachedRefinedType - RefinedType(...)
[error]    |    at izumi.reflect.dottyreflection.Inspector.inspectTypeRepr(Inspector.scala:96)
[error]    |    at izumi.reflect.dottyreflection.Inspector.buildTypeRef(Inspector.scala:22)
[error]    |    at izumi.reflect.dottyreflection.TypeInspections$.apply(TypeInspections.scala:10)
[error]    |    at izumi.reflect.dottyreflection.Inspect$.inspectAny(Inspect.scala:18)
```

Here's a minimal project to reproduce the issue:

*build.sbt:*

```scala
scalaVersion := "3.1.0"
libraryDependencies += "dev.zio" %% "zio" % "2.0.0-M6-2"
```

*project/build.properties:*

```
sbt.version=1.5.5
```

*src/main/scala/Foo.scala:*

```scala
object Bar:
  trait Service:
    def bar(): zio.Task[Int]

object Foo:
  val http: zio.ULayer[Bar.Service] =
    zio.ZLayer.succeed { // doesn't work
    // zio.ZLayer.succeed[Bar.Service] { // works
      new Bar.Service:
        def bar(): zio.UIO[Int] = zio.ZIO.succeed(42)
    }
```

[1]: https://github.com/earldouglas/sectery/pull/292/files#diff-5fc55b0d1a0f4b318d959097aaf698a5a2073e63f6d5fb52b37a63e88863a0d9R14

### PR DESCRIPTION
**Pull request by kitlangton**
Fixes https://github.com/zio/zio/issues/6071

Followed @neko-kai's recommendation. Not sure how dangerous it is 😄.
We're not handling structural/`Refined` types for Dotty at the moment it seems. This is A-Okay for zio's purposes at the moment, but just wanted to double check.

Seems like there might be a Dotty bug here as well, as trying to do `case r: Refined => r.tpt` blows up.

### CODE REVIEW

**Comment by pshirshov** [comment]
I would use structural refinement instead of direct usage of java reflection. Apart of that it should be fine.

**Comment by kitlangton** [comment]
Oh woah. I didn't know that would work :O

**Comment by pshirshov** [comment]
It should, refinements rely on reflection and perfectly ignore accessibility modifiers.

**Review by pshirshov — APPROVED** [review]

File: izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspector.scala [hunk 1]
```diff
@@ -91,6 +91,10 @@ abstract class Inspector(protected val shift: Int) extends InspectorBase {
         log(s"TYPEREPR UNSUPPORTED: LazyRef occured $lazyref")
         NameReference("???")
 
+      // Matches CachedRefinedType for this ZIO issue https://github.com/zio/zio/issues/6071
+      case ref: Refined { def parent: TypeRepr } =>
```
Comment (neko-kai) [inline izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspector.scala]: @kitlangton Refined is a TypeTree, not a TypeRepr so this match can never match - except that it's skipped due to additional refinement. Actually the reflective access seems unnecessary - the `.parent` method is public in `RefinementMethods`, so it should probably work with
```suggestion
      case ref: Refinement =>
```

Comment (kitlangton) [reply izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/dottyreflection/Inspector.scala]: Oops! Good catch :)

**Comment by neko-kai** [comment]
Thank you! 🙏

**Comment by earldouglas** [comment]
Thanks!
